#! /bin/sh
exec trayer --edge top --align right --SetDockType true --SetPartialStrut true --expand true --width 10 --transparent true --tint 0x000000 --alpha 0 --heighttype pixel --height 19 &
exec gnome-session --session xmonad "$@"
